FROM ubuntu:24.04

RUN apt-get -y update && apt-get -y upgrade
RUN apt-get install -y openjdk-11-jdk

ARG APP_JAR=https-api-0.0.1-SNAPSHOT.jar
EXPOSE 8443

COPY build/libs/${APP_JAR} /app/ROOT.jar
WORKDIR /app
ENTRYPOINT ["java", "-jar", "ROOT.jar"]
