server:
  port: 8080

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-components: always
  #      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.example: debug
