server:
  port: 18081

spring:
  application:
    name: downstream-service
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://collector:4317

priceClient:
  baseUrl: http://upstream-service:18080