FROM amazoncorretto:8-alpine-jdk

WORKDIR /app

COPY ./otelagent/opentelemetry-javaagent.jar .
COPY ./build/libs/demo-0.0.1-SNAPSHOT.jar .

EXPOSE 8080

CMD ["java", "-javaagent:./opentelemetry-javaagent.jar", "-jar", "./demo-0.0.1-SNAPSHOT.jar"]